---
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps): ⚛︎ update"
    labels:
      - "chore"
      - "dependencies"
    groups:
      patches:
        patterns:
          - "*"
        update-types:
          - patch
      minors:
        patterns:
          - "*"
        update-types:
          - minor
      majors:
        patterns:
          - "*"
        update-types:
          - major
  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(tools deps): ⚛︎ update"
    labels:
      - "tools"
      - "chore"
      - "dependencies"
    groups:
      patches:
        patterns:
          - "*"
        update-types:
          - patch
      minors:
        patterns:
          - "*"
        update-types:
          - minor
      majors:
        patterns:
          - "*"
        update-types:
          - major
