### Post generate Pilot NPC
POST http://localhost:8787/api/npcs/single
Content-Type: application/json

{
  "role": "pilot",
  "citizen_category": "average",
  "experience": "regular",
  "gender": "unspecified"
}
###