### Post generate Pilot female NPC
POST http://localhost:8787/api/npcs/single
Content-Type: application/json

{
  "role": "gunner",
  "citizen_category": "above_average",
  "experience": "veteran",
  "gender": "female"
}

### Post generate Pilot male NPC
POST http://localhost:8787/api/npcs/single
Content-Type: application/json

{
  "role": "pilot",
  "citizen_category": "average",
  "experience": "regular",
  "gender": "male"
}

### Post generate Pilot NPC without specifying the gender
POST http://localhost:8787/api/npcs/single
Content-Type: application/json

{
  "role": "pilot",
  "citizen_category": "average",
  "experience": "regular"
}

### Method not allowed
GET http://localhost:8787/api/npcs/single

### Role is required
POST http://localhost:8787/api/npcs/single
Content-Type: application/json

{
  "citizen_category": "average",
  "experience": "regular",
  "gender": "unspecified"
}
###
